---
application:
  name: "git-microservices-analyzer-server"
  project: "git-microservices-analyzer-server"
  organization: "QoveryCommunity"
routers:
- name: "main-git-microservices-analyzer-server"
  routes:
  - application_name: "git-microservices-analyzer-server"
    paths:
    - "/*"
